; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.x"

; Modules
projects[admin_menu][version] = "3.0-rc3"

projects[ctools][version] = "1.2"

projects[devel][version] = "1.3"

projects[panels][version] = "3.3"

projects[pathauto][version] = "1.2"

projects[token][version] = "1.4"

projects[views][version] = "3.5"

; Themes
projects[omega][version] = "3.1"

